export interface Feature {
    id: number;
    name: string;
    category: string;
    isStarred: boolean;
}

export const ALL_300_FEATURES: Feature[] = [
    { id: 1, name: "معالج الإعداد /setup", category: "التحكم والإعداد والربط", isStarred: false },
    { id: 2, name: "خزنة المفاتيح المشفرة", category: "التحكم والإعداد والربط", isStarred: false },
    { id: 3, name: "معالج الربط /connect", category: "التحكم والإعداد والربط", isStarred: false },
    { id: 4, name: "إضافة مفاتيح AI", category: "التحكم والإعداد والربط", isStarred: false },
    { id: 5, name: "حالة الخزنة", category: "التحكم والإعداد والربط", isStarred: false },
    { id: 6, name: "إدارة الموصلات", category: "التحكم والإعداد والربط", isStarred: false },
    { id: 7, name: "ربط GitHub", category: "التحكم والإعداد والربط", isStarred: false },
    { id: 8, name: "ربط GitLab", category: "التحكم والإعداد والربط", isStarred: false },
    { id: 9, name: "ربط Railway", category: "التحكم والإعداد والربط", isStarred: false },
    { id: 10, name: "ربط Vercel", category: "التحكم والإعداد والربط", isStarred: false },
    { id: 11, name: "ربط Slack Webhook", category: "التحكم والإعداد والربط", isStarred: false },
    { id: 12, name: "ربط Discord Webhook", category: "التحكم والإعداد والربط", isStarred: false },
    { id: 13, name: "ربط Notion", category: "التحكم والإعداد والربط", isStarred: false },
    { id: 14, name: "دعم SQLite المؤقت", category: "التحكم والإعداد والربط", isStarred: false },
    { id: 15, name: "دعم Postgres", category: "التحكم والإعداد والربط", isStarred: false },
    { id: 16, name: "إنشاء مشروع جديد /newproject", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 17, name: "التبدل بين المشاريع /switch", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 18, name: "تصدير المشروع", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 19, name: "حذف المشروع", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 20, name: "دعم Supabase", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 21, name: "دعم Monorepo", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 22, name: "وضع النطاق المحدود /scope", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 23, name: "مزامنة Delta Sync", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 24, name: "أرشفة المشاريع", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 25, name: "استنساخ المشاريع", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 26, name: "قوالب المشاريع الجاهزة", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 27, name: "إدارة بيئات العمل", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 28, name: "متغيرات البيئة المشفرة", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 29, name: "نسخ احتياطي تلقائي للمشاريع", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 30, name: "استعادة النسخ الاحتياطية", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 31, name: "تجميد المشروع", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 32, name: "إلغاء تجميد المشروع", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 33, name: "مشاركة المشروع", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 34, name: "نقل ملكية المشروع", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 35, name: "عرض تفاصيل المشروع", category: "إدارة المشاريع والبيئات", isStarred: false },
    { id: 36, name: "وكيل المهندس المعماري", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 37, name: "وكيل المبرمج", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 38, name: "وكيل المختبر", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 39, name: "وكيل الناقد", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 40, name: "وكيل الموثق", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 41, name: "وكيل المحلل", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 42, name: "وكيل المحسن", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 43, name: "وكيل المدمج", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 44, name: "وكيل الحارس", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 45, name: "وكيل المترجم", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 46, name: "إنشاء وكلاء مخصصين", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 47, name: "تعديل تعليمات الوكلاء", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 48, name: "حذف وكلاء مخصصين", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 49, name: "تفعيل/تعطيل وكلاء", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 50, name: "ترتيب أولوية الوكلاء", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 51, name: "وضع النقاش الجماعي", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 52, name: "وضع التصويت بين الوكلاء", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 53, name: "وكيل مراجعة الأمان", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 54, name: "وكيل تحسين الأداء", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 55, name: "وكيل تحليل التعقيد", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 56, name: "وكيل كتابة الاختبارات", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 57, name: "وكيل توليد البيانات الوهمية", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 58, name: "وكيل ترجمة الواجهات", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 59, name: "وكيل تحسين قواعد البيانات", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 60, name: "وكيل إدارة الحزم", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 61, name: "وكيل تحليل الذاكرة", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 62, name: "وكيل فحص التبعيات", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 63, name: "وكيل ترقية المكتبات", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 64, name: "وكيل تنظيف الكود", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 65, name: "وكيل توحيد الأنماط", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 66, name: "وكيل توليد الـ README", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 67, name: "وكيل كتابة الـ Changelog", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 68, name: "وكيل تحليل الـ Git History", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 69, name: "وكيل التنبؤ بالأخطاء", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 70, name: "وكيل اقتراح البنية", category: "مصفوفة الوكلاء الذكية", isStarred: false },
    { id: 71, name: "الفهرسة التلقائية للملفات", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 72, name: "محرك الاسترجاع RAG", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 73, name: "البحث في الكود", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 74, name: "عرض الملفات", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 75, name: "تعديل ملف محدد", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 76, name: "إنشاء ملف جديد", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 77, name: "حذف ملف", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 78, name: "إعادة تسمية ملف", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 79, name: "نقل ملف", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 80, name: "نسخ ملف", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 81, name: "دمج ملفات", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 82, name: "تقسيم ملفات", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 83, name: "استخراج دالة", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 84, name: "تضمين دالة", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 85, name: "إعادة هيكلة الكود", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 86, name: "تحويل الكود", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 87, name: "تحديث بناء الجملة", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 88, name: "إضافة تعليقات ذكية", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 89, name: "إزالة التعليقات الميتة", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 90, name: "توليد أكواد أولية", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 91, name: "توليد واجهات API", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 92, name: "توليد نماذج البيانات", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 93, name: "توليد مسارات", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 94, name: "توليد وحدات التحكم", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 95, name: "توليد خدمات", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 96, name: "توليد مستمعات", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 97, name: "توليد وحدات", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 98, name: "توليد مكونات UI", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 99, name: "توليد أنماط CSS", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 100, name: "توليد استعلامات SQL", category: "أدوات معالجة الملفات والكود", isStarred: false },
    { id: 101, name: "نظام الـ Checkpoint", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 102, name: "نظام الـ Diff والمراجعة", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 103, name: "التراجع /rollback", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 104, name: "اللقطات /snapshots", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 105, name: "تشغيل اختبارات الوحدة", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 106, name: "تشغيل اختبارات التكامل", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 107, name: "تشغيل اختبارات E2E", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 108, name: "توليد اختبارات تلقائية", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 109, name: "تحليل تغطية الكود", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 110, name: "عزل الاختبارات المعزولة", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 111, name: "محاكاة الـ APIs", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 112, name: "حقن الأخطاء", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 113, name: "تتبع الأخطاء", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 114, name: "تحليل Stack Trace", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 115, name: "اقتراح إصلاحات الأخطاء", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 116, name: "تشغيل الكود في Sandbox", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 117, name: "عرض مخرجات الـ Console", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 118, name: "التقاط لقطات شاشة للـ UI", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 119, name: "مقارنة لقطات الشاشة", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 120, name: "فحص تسرب الذاكرة", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 121, name: "فحص تسرب الموارد", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 122, name: "تحليل أداء الاختبارات", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 123, name: "تخطي الاختبارات الفاشلة", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 124, name: "إعادة تشغيل الاختبارات", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 125, name: "تصدير تقارير الاختبارات", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: false },
    { id: 126, name: "إدارة الميزانية", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 127, name: "عرض الخصوصية", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 128, name: "الحذف الشامل /reset_all", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 129, name: "فحص الثغرات الأمنية", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 130, name: "فحص التبعيات المهملة", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 131, name: "فحص تسرب المفاتيح", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 132, name: "فحص حقن SQL", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 133, name: "فحص XSS", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 134, name: "فحص CSRF", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 135, name: "فحص CORS", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 136, name: "فحص Rate Limiting", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 137, name: "توليد سياسات CSP", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 138, name: "تشفير البيانات الحساسة", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 139, name: "إدارة صلاحيات الملفات", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 140, name: "سجل التدقيق", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 141, name: "تنبيهات الأمان الفورية", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 142, name: "فحص التهيئة الخاطئة", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 143, name: "فحص الشهادات SSL", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 144, name: "فحص بروتوكولات الشبكة", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 145, name: "توليد تقارير الامتثال", category: "إدارة الأمان والامتثال", isStarred: false },
    { id: 146, name: "إنشاء جداول تلقائية", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 147, name: "تعديل مخططات الجداول", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 148, name: "حذف الجداول", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 149, name: "توليد بذور البيانات", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 150, name: "توليد المصانع", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 151, name: "تحسين الاستعلامات", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 152, name: "إضافة فهارس", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 153, name: "تحليل الفهارس الحالية", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 154, name: "نسخ احتياطي لقاعدة البيانات", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 155, name: "استعادة قاعدة البيانات", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 156, name: "ترحيل البيانات", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 157, name: "توليد أكواد الترحيل", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 158, name: "التراجع عن الترحيل", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 159, name: "فحص تكامل البيانات", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 160, name: "تنظيف البيانات المكررة", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 161, name: "أرشفة السجلات القديمة", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 162, name: "تقسيم الجداول", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 163, name: "تجميع الجداول", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 164, name: "مراقبة اتصالات قاعدة البيانات", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 165, name: "تحليل بطء الاستعلامات", category: "التحكم بقواعد البيانات والمخططات", isStarred: false },
    { id: 166, name: "ربط المستودعات", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 167, name: "سحب التغييرات", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 168, name: "دفع التغييرات", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 169, name: "إنشاء فروع", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 170, name: "التبديل بين الفروع", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 171, name: "دمج الفروع", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 172, name: "إعادة_base", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 173, name: "حل تعارضات الدمج", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 174, name: "إنشاء طلبات سحب", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 175, name: "مراجعة طلبات السحب", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 176, name: "دمج طلبات السحب", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 177, name: "إغلاق طلبات السحب", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 178, name: "إدارة Issues", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 179, name: "إنشاء Issues تلقائية", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 180, name: "ربط Issues بالـ Commits", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 181, name: "توليد رسائل Commit ذكية", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 182, name: "تطبيق Conventional Commits", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 183, name: "إدارة العلامات", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 184, name: "إنشاء إصدارات", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 185, name: "توليد ملاحظات الإصدار", category: "عمليات غيت والتحكم بالإصدارات", isStarred: false },
    { id: 186, name: "توليد ملفات Dockerfile", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 187, name: "توليد docker-compose", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 188, name: "بناء الصور", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 189, name: "دفع الصور للسجلات", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 190, name: "توليد GitHub Actions", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 191, name: "توليد GitLab CI", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 192, name: "نشر تلقائي للـ Staging", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 193, name: "نشر تلقائي للـ Production", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 194, name: "التراجع عن النشر", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 195, name: "نشر Blue-Green", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 196, name: "نشر Canary", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 197, name: "نشر Rolling Update", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 198, name: "إدارة البيئات السحابية", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 199, name: "ربط نطاقات", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 200, name: "توليد شهادات SSL", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 201, name: "إدارة متغيرات بيئة النشر", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 202, name: "مراقبة حالة النشر", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 203, name: "إشعارات فشل النشر", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 204, name: "سجل عمليات النشر", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 205, name: "اختبار ما قبل النشر", category: "حاويات دوكر وأتمتة خطوط الإمداد", isStarred: false },
    { id: 206, name: "المساعدة /help", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 207, name: "أزرار Inline للموافقة", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 208, name: "قوائم الأوامر السريعة", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 209, name: "رسائل التأكيد التفاعلية", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 210, name: "عرض الكود بتنسيق Markdown", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 211, name: "عرض الصور والمخططات", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 212, name: "إرسال الملفات المباشرة", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 213, name: "تحميل الملفات من تيليجرام", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 214, name: "معالجة الرسائل الصوتية", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 215, name: "معالجة الصور OCR", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 216, name: "معالجة المستندات PDF", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 217, name: "وضع المحادثة المستمر", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 218, name: "إلغاء المهام الحالية", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 219, name: "إيقاف البوت مؤقتاً", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 220, name: "استئناف البوت", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 221, name: "إشعارات التقدم", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 222, name: "رسائل الحالة الحية", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 223, name: "تصفح المجلدات تفاعلياً", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 224, name: "محرر أكواد مصغر", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 225, name: "اختصارات لوحة المفاتيح", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 226, name: "حالة المهمة", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 227, name: "تنفيذ المهمة", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: false },
    { id: 228, name: "عرض السجلات", category: "سجلات النظام ومراقبة الموارد", isStarred: false },
    { id: 229, name: "تصفية السجلات", category: "سجلات النظام ومراقبة الموارد", isStarred: false },
    { id: 230, name: "البحث في السجلات", category: "سجلات النظام ومراقبة الموارد", isStarred: false },
    { id: 231, name: "تصدير السجلات", category: "سجلات النظام ومراقبة الموارد", isStarred: false },
    { id: 232, name: "مسح السجلات القديمة", category: "سجلات النظام ومراقبة الموارد", isStarred: false },
    { id: 233, name: "مراقبة استخدام الـ CPU", category: "سجلات النظام ومراقبة الموارد", isStarred: false },
    { id: 234, name: "مراقبة استخدام الـ RAM", category: "سجلات النظام ومراقبة الموارد", isStarred: false },
    { id: 235, name: "مراقبة استخدام القرص", category: "سجلات النظام ومراقبة الموارد", isStarred: false },
    { id: 236, name: "مراقبة استخدام الشبكة", category: "سجلات النظام ومراقبة الموارد", isStarred: false },
    { id: 237, name: "تنبيهات استنفاد الموارد", category: "سجلات النظام ومراقبة الموارد", isStarred: false },
    { id: 238, name: "إحصائيات استخدام البوت", category: "سجلات النظام ومراقبة الموارد", isStarred: false },
    { id: 239, name: "إحصائيات تكلفة الـ API", category: "سجلات النظام ومراقبة الموارد", isStarred: false },
    { id: 240, name: "تقارير الأداء الأسبوعية", category: "سجلات النظام ومراقبة الموارد", isStarred: false },
    { id: 241, name: "تحسين الـ Prompts تلقائياً", category: "تحليلات اللغات والنوايا الذكية", isStarred: false },
    { id: 242, name: "حفظ الـ Prompts المفضلة", category: "تحليلات اللغات والنوايا الذكية", isStarred: false },
    { id: 243, name: "مكتبة الـ Prompts", category: "تحليلات اللغات والنوايا الذكية", isStarred: false },
    { id: 244, name: "تحليل نية المستخدم", category: "تحليلات اللغات والنوايا الذكية", isStarred: false },
    { id: 245, name: "تفكيك المهام المعقدة", category: "تحليلات اللغات والنوايا الذكية", isStarred: false },
    { id: 246, name: "التعلم من تصحيحات المستخدم", category: "تحليلات اللغات والنوايا الذكية", isStarred: false },
    { id: 247, name: "تكييف أسلوب الكتابة", category: "تحليلات اللغات والنوايا الذكية", isStarred: false },
    { id: 248, name: "اقتراحات السياق", category: "تحليلات اللغات والنوايا الذكية", isStarred: false },
    { id: 249, name: "تلخيص المحادثات الطويلة", category: "تحليلات اللغات والنوايا الذكية", isStarred: false },
    { id: 250, name: "استخراج المتطلبات من النصوص", category: "تحليلات اللغات والنوايا الذكية", isStarred: false },
    { id: 251, name: "⭐ أولوية في الطابور", category: "مصفوفة الوكلاء الذكية", isStarred: true },
    { id: 252, name: "⭐ جولات نقاش إضافية", category: "مصفوفة الوكلاء الذكية", isStarred: true },
    { id: 253, name: "⭐ وكلاء مخصصون إضافيون", category: "مصفوفة الوكلاء الذكية", isStarred: true },
    { id: 254, name: "⭐ مشاريع نشطة متزامنة", category: "مصفوفة الوكلاء الذكية", isStarred: true },
    { id: 255, name: "⭐ مهام مجدولة Cron", category: "إعدادات وجدولة وتصدير التقارير", isStarred: true },
    { id: 256, name: "⭐ تقارير PDF منسقة", category: "إعدادات وجدولة وتصدير التقارير", isStarred: true },
    { id: 257, name: "⭐ تقارير HTML منسقة", category: "إعدادات وجدولة وتصدير التقارير", isStarred: true },
    { id: 258, name: "⭐ سجل ممتد 90 يوم", category: "إعدادات وجدولة وتصدير التقارير", isStarred: true },
    { id: 259, name: "⭐ واجهة رسائل مخصصة", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: true },
    { id: 260, name: "⭐ دعم أولوية", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: true },
    { id: 261, name: "⭐ وضع التركيز العميق", category: "مصفوفة الوكلاء الذكية", isStarred: true },
    { id: 262, name: "⭐ مولد المخططات البصرية", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: true },
    { id: 263, name: "⭐ وضع الشرح التفاعلي", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: true },
    { id: 264, name: "⭐ وضع اكتشاف الأخطاء", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: true },
    { id: 265, name: "⭐ الأوامر الصوتية", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: true },
    { id: 266, name: "⭐ الإصلاح الذاتي Sandbox", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: true },
    { id: 267, name: "⭐ مشاركة اللقطات", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: true },
    { id: 268, name: "⭐ البطّة المطاطية التفاعلية", category: "مصفوفة الوكلاء الذكية", isStarred: true },
    { id: 269, name: "⭐ وضع المحامي الشيطان", category: "مصفوفة الوكلاء الذكية", isStarred: true },
    { id: 270, name: "⭐ وكيل المترجم الفوري ELI5", category: "مصفوفة الوكلاء الذكية", isStarred: true },
    { id: 271, name: "⭐ وضع الشوي اللطيف Roast", category: "مصفوفة الوكلاء الذكية", isStarred: true },
    { id: 272, name: "⭐ نظام RPG للمطورين", category: "المرح وتصميم ألعاب المطورين", isStarred: true },
    { id: 273, name: "⭐ مولد ميمز الأخطاء", category: "المرح وتصميم ألعاب المطورين", isStarred: true },
    { id: 274, name: "⭐ أساطير الكود Lore", category: "المرح وتصميم ألعاب المطورين", isStarred: true },
    { id: 275, name: "⭐ استراحة القهوة الذكية", category: "المرح وتصميم ألعاب المطورين", isStarred: true },
    { id: 276, name: "⭐ الفريق الأحمر Red Team", category: "إدارة الأمان والامتثال", isStarred: true },
    { id: 277, name: "⭐ آلة الزمن للأخطاء", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: true },
    { id: 278, name: "⭐ محاكي السيناريوهات", category: "المرح وتصميم ألعاب المطورين", isStarred: true },
    { id: 279, name: "⭐ عالم آثار الكود", category: "المرح وتصميم ألعاب المطورين", isStarred: true },
    { id: 280, name: "⭐ عراف المكتبات", category: "المرح وتصميم ألعاب المطورين", isStarred: true },
    { id: 281, name: "⭐ زر الذعر Panic Button", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: true },
    { id: 282, name: "⭐ التطور التلقائي Auto-Evolution", category: "التحسين التلقائي والتطور", isStarred: true },
    { id: 283, name: "⭐ ساحة اللعب التلقائية", category: "الاختبار والتصحيح والبيئة الافتراضية", isStarred: true },
    { id: 284, name: "⭐ مقياس صحة الكود", category: "المرح وتصميم ألعاب المطورين", isStarred: true },
    { id: 285, name: "⭐ البرمجة الجماعية Multiplayer", category: "الواجهة التفاعلية والأوامر الذكية", isStarred: true },
    { id: 286, name: "⭐ راوي قصص الـ PR", category: "عمليات غيت والتحكم بالإصدارات", isStarred: true },
    { id: 287, name: "⭐ كشاف التكرار", category: "أدوات معالجة الملفات والكود", isStarred: true },
    { id: 288, name: "⭐ عرض المصفوفة Matrix View", category: "المرح وتصميم ألعاب المطورين", isStarred: true },
    { id: 289, name: "⭐ الذاكرة الأسلوبية", category: "تحليلات اللغات والنوايا الذكية", isStarred: true },
    { id: 290, name: "⭐ الوضع الليلي للوكلاء", category: "سجلات النظام ومراقبة الموارد", isStarred: true },
    { id: 291, name: "⭐ حوض التوكنات Token Pool", category: "حوض التوكنات وتوجيه الاستهلاك", isStarred: true },
    { id: 292, name: "⭐ التوجيه الذكي للنماذج", category: "حوض التوكنات وتوجيه الاستهلاك", isStarred: true },
    { id: 293, name: "⭐ توقع استهلاك التوكنات", category: "حوض التوكنات وتوجيه الاستهلاك", isStarred: true },
    { id: 294, name: "⭐ التبديل بين المزودين", category: "حوض التوكنات وتوجيه الاستهلاك", isStarred: true },
    { id: 295, name: "⭐ لوحة التكلفة الحية", category: "حوض التوكنات وتوجيه الاستهلاك", isStarred: true },
    { id: 296, name: "⭐ مولد المخطط الشامل Blueprint", category: "المعالجات المعمارية المتقدمة", isStarred: true },
    { id: 297, name: "⭐ وضع بناء البوتات Bot Builder", category: "المعالجات المعمارية المتقدمة", isStarred: true },
    { id: 298, name: "⭐ مهندس الـ APIs التلقائي", category: "المعالجات المعمارية المتقدمة", isStarred: true },
    { id: 299, name: "⭐ سجل القرارات المعمارية ADR", category: "المعالجات المعمارية المتقدمة", isStarred: true },
    { id: 300, name: "⭐ تحليل الحمض النووي للكود", category: "المعالجات المعمارية المتقدمة", isStarred: true }
];
