import { BaseAgent } from '../../agents/BaseAgent';
import { botDb } from '../../db/botDb';
import * as fs from 'fs';
import * as path from 'path';

export interface FeatureContext {
    userId: number;
    projectPath?: string;
    chatContext?: any;
    arg?: string;
}

export const feature_16 = {
    id: 16,
    name: "إنشاء مشروع جديد /newproject",
    category: "إدارة المشاريع والبيئات",
    isStarred: false,
    async run(context: FeatureContext): Promise<string> {
        const name = context.arg || "NewApp";
        const cleanName = name.replace(/[^a-zA-Z0-9_-]/g, "");
        const projectPath = path.join(process.cwd(), "projects", cleanName);
        
        try {
            if (!fs.existsSync(projectPath)) {
                fs.mkdirSync(projectPath, { recursive: true });
            }
            
            // Initialize with basic package.json
            const packageJson = {
                name: cleanName.toLowerCase(),
                version: "1.0.0",
                description: "Created by OmniMind OS",
                main: "dist/index.js",
                scripts: {
                    build: "tsc",
                    start: "node dist/index.js"
                },
                dependencies: {}
            };
            fs.writeFileSync(path.join(projectPath, "package.json"), JSON.stringify(packageJson, null, 2));
            fs.mkdirSync(path.join(projectPath, "src"), { recursive: true });
            fs.writeFileSync(path.join(projectPath, "src", "index.ts"), `console.log("Welcome to ${cleanName} generated by OmniMind OS!");\n`);
            
            await botDb.createProject(context.userId, cleanName, projectPath);
            
            return `🏗️ *تم إنشاء مشروع جديد بنجاح!* 🏗️
━━━━━━━━━━━━━━━━━━━━━━━━━
📁 *الاسم:* \`${cleanName}\`
📍 *المسار:* \`${projectPath}\`
🟢 *الحالة:* نشط وجاهز للتطوير

⚙️ *تم توليد الملفات الأساسية:*
• \`package.json\` (معد ومضبوط)
• \`src/index.ts\` (نقطة الدخول للمشروع)

💡 البوت جاهز الآن لكتابة وتعديل الأكواد في هذا المشروع تلقائياً!`;
        } catch (err: any) {
            return `❌ فشل إنشاء المشروع: ${err.message}`;
        }
    }
};
